### ISSUE TITLE
feat: the statements for loops

### ISSUE THREAD

**Issue by BrianLe188** [BrianLe188/condition-component#3]
- [x] map
- [x] filter

**Comment by louisntnt** [comment]
I think in this version we just need to do for..of, for..in, break, continute to check if they match and then continue to do the rest.
And finally, the for statement is not needed because we have for..of and in to do the for loop

**Comment by BrianLe188** [comment]
hmm, good idea.
i have though a lot about it. i will add the map and filter feature first cause we use many map and filter function to render.
for..of, for..in also good but i have never seen someone use for loop for render

**Comment by BrianLe188** [comment]
Done
